### ISSUE TITLE
feat: Create a GH Action to deploy on AWS

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/gh-action#1]
Create a github action to deploy your tailcall configuration on AWS:

```yml
- uses: tailcall/gh-action
  with:
    deploy:
      - aws:
        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        config: ./tailcall.graphql
```

**Technical Requirements**
- Keep the action clean and reusable for other partners.
- Ensure enough unit tests have been added for the actions.
- Deployment should be on AWS Lambda and publicly accessible
- The tailcall configuration should be picked up from the repo.
- Ensure the user experience is simple & smooth.

**Additional Information**
- https://github.com/tailcallhq/tailcall-on-aws
